version: "3.8"
services:
  web:
    container_name: front_croissants
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      # - VITE_REACT_APP_STRAPI_API_ENDPOINT=http://strapi:1337
      - VITE_REACT_APP_STRAPI_API_ENDPOINT=https://strapi.dbakersdev.ovh
    networks:
      - croissants

networks:
  croissants:
    external:
      name: croissants